{% set name = "ldas-tools-al-swig" %}
{% set version = "2.6.9" %}
{% set sha256 = "2d4c3451e82c18b6c2a300f8a894066eb16dd471a731c17fce604117504d1d65" %}

{% set ldas_tools_cmake_version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [not win]
    - make  # [not win]
    - swig
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}

test:
  commands:
    - test -f ${PREFIX}/include/ldastoolsal/gpstime.i  # [not win]

outputs:
  - name: ldas-tools-al-swig
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: SWIG bindings for the LDAS Tools abstraction toolkit

  - name: python-ldas-tools-al
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [unix]
        - make  # [unix]
        - swig
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - python
      run:
        - python
    test:
      imports:
        - LDAStools
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools abstraction toolkit

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG bindings for the LDAS Tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
