{% set name = "ldas-tools-al-swig" %}
{% set version = "2.6.11" %}

# dependency versions
{% set ldas_tools_cmake_version = "1.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 3225e39d674b44b291f4e8fddd0037eef8efe63c4dca488dde139830cd511e3c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.6
    - pkg-config  # [not win]
    - make  # [not win]
    - swig
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}

test:
  commands:
    - test -f ${PREFIX}/include/ldastoolsal/gpstime.i  # [not win]

outputs:
  - name: ldas-tools-al-swig
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: SWIG bindings for the LDAS Tools abstraction toolkit

  - name: python-ldas-tools-al
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - cmake >=3.6
        - make  # [unix]
        - pkg-config  # [unix]
        - swig
        # extras for cross compilation
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - python
      run:
        - python
    test:
      imports:
        - LDAStools
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools abstraction toolkit

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: SWIG bindings for the LDAS Tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
