{% set name = "ldas-tools-al-swig" %}
{% set version = "2.6.7" %}
{% set sha256 = "bd41eaf7b85297f77d28eb5c2578f040e68934c14054f4c6fab8c71645d21966" %}

{% set ldas_tools_cmake_version = "1.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [not win]
    - make  # [not win]
    - swig
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}

test:
  commands:
    - test -f ${PREFIX}/include/ldastoolsal/gpstime.i  # [not win]

outputs:
  - name: ldas-tools-al-swig

  - name: python-ldas-tools-al
    script: install-python.sh
    build:
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
        - swig
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - python
      run:
        - python
    test:
      imports:
        - LDAStools
    about:
      home: https://wiki.ligo.org/Computing/LDASTools
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools abstraction toolkit

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: SWIG bindings for the LDAS Tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
