{% set name = "ldas-tools-al-swig" %}
{% set version = "2.6.5" %}
{% set sha256 = "32250c932360c509ced6f5efcbdd2379535b0f8b869313cae0cce40883f7c875" %}
{% set ldas_tools_cmake_version = "1.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.6
    - pkg-config  # [not win]
    - make  # [not win]
    - swig
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}

outputs:
  - name: python-ldas-tools-al
    script: install-python.sh  # [not win]
    script: install-python.bat  # [win]
    build:
      activate_in_script: true
    requirements:
      build:
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
        - swig
      host:
        - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
        - python
      run:
        - python
    test:
      imports:
        - LDAStools
    about:
      home: https://docs.ligo.org/ldastools/LDAS_Tools/Beta/doc/ldas-tools-al/ldastoolsal/html/
      dev_url: https://git.ligo.org/ldastools/LDAS_Tools
      doc_url: https://docs.ligo.org/ldastools/LDAS_Tools/Beta/doc/ldas-tools-al/ldastoolsal/html/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: Python bindings for the LDAS Tools abstraction toolkit

about:
  home: https://docs.ligo.org/ldastools/LDAS_Tools/Beta/doc/ldas-tools-al/ldastoolsal/html/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: SWIG bindings for the LDAS Tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
